/** Nyx Virell catalog seed — three parallel covered cyber-editorial sets.
 *  Multi-muse design: each muse owns ladder rows via model_id (unique shot ids).
 *  Assets cleared Imagine moderation as covered editorial (chrome mesh / violet
 *  lace / bodysuit) — copy must not promise a full-nude climax.
 */

import type { SeedLadder } from "./catalog-seed";

const P = {
  1: 499,
  2: 699,
  3: 899,
  4: 1199,
  5: 1499,
  6: 1799,
  7: 2299,
  8: 2799,
  9: 3699,
} as const;

export const NYX_MODEL_ID = "mod_nyx";

export const NYX_SEED_LADDERS: SeedLadder[] = [
  {
    id: "lad_nyx_reveal",
    slug: "nyx-the-reveal",
    title: "The Reveal",
    theme: "frontal",
    tagline: "Chrome mesh. Violet lace. She faces you — covered cyber editorial, in order.",
    description:
      "Doorway neon. Liquid-chrome mesh robe. Electric-violet cyber lace. Nine frontal beats — covered editorial undress she cleared for the vault. No nude promise; the charge is the chrome failing on her terms.",
    cover: "/media/nyx-00-the-reveal-cover.jpg",
    sort: 4,
    collectors: 0,
    climax: 0,
    discount: 0.32,
    shots: [
      {
        id: "nyx_rev_1",
        step: 1,
        title: "The Invitation",
        tease:
          "Nyx in the doorway, liquid-chrome mesh robe tied closed, void lipstick catching neon. Cheapest beat. Shot 2 is the first time the mesh moves.",
        grant: "Shot 1 unlocked. She already decided whether you stay.",
        story:
          "The look is how she lets you in. The robe only slips for collectors who pay to watch chrome move. That's Shot 2.",
        drop: "",
        media: "grant:nyx_rev_1.jpg",
        type: "photo",
        pos: "center top",
        price: P[1],
      },
      {
        id: "nyx_rev_2",
        step: 2,
        title: "The Robe",
        tease:
          "Chrome mesh off one shoulder — still covered. Violet cyber lace only suggested under the robe. Shot 3 she sits in the lace.",
        grant: "The mesh slipped for you. Not for a room.",
        story:
          "A moving robe is her stalling, and she knows it. Violet lace is underneath. That's Shot 3.",
        drop: "38% bounce after the doorway. She priced the slip to drop them.",
        media: "grant:nyx_rev_2.jpg",
        type: "photo",
        pos: "center",
        price: P[2],
      },
      {
        id: "nyx_rev_3",
        step: 3,
        title: "Lace",
        tease:
          "Electric-violet cyber lace. Hands in her lap. No smile. Piercings catch light. Shot 4 she sits on the bed.",
        grant: "You have the lace. Most men stop here.",
        story:
          "Lace is the test, not the gift. Shot 4 she sits for collectors who don't rush the neon.",
        drop: "51% never make it past lace. That's a filter.",
        media: "grant:nyx_rev_3.jpg",
        type: "photo",
        pos: "center",
        price: P[3],
      },
      {
        id: "nyx_rev_4",
        step: 4,
        title: "The Edge",
        tease:
          "On the bed edge. Robe open over violet lace — covered editorial, private neon. Shot 5 is the look she withholds.",
        grant: "You have the edge of her bed. The chosen look starts at Shot 5.",
        story:
          "Sitting down is how she closes the door. Shot 5 is eye contact — LED ink and piercings, still covered.",
        drop: "61% never see her sit. They wanted a nude drop. She sells chrome.",
        media: "grant:nyx_rev_4.jpg",
        type: "photo",
        pos: "center 30%",
        price: P[4],
      },
      {
        id: "nyx_rev_5",
        step: 5,
        title: "Chosen",
        tease:
          "Tight portrait. Withheld eye contact. Silver piercings + LED collarbone circuitry. Shot 6 she lets the mesh breathe — six seconds.",
        grant: "She's looking at you. Not a feed.",
        story:
          "Eye contact is rarer than lace. Motion is rarer than that. Shot 6 is six seconds of chrome she will not reshoot.",
        drop: "70% never get this look.",
        media: "grant:nyx_rev_5.jpg",
        type: "photo",
        pos: "center top",
        price: P[5],
      },
      {
        id: "nyx_rev_6",
        step: 6,
        title: "The Breath",
        tease:
          "Mid-motion. Chrome mesh shifting. Six-second clip energy — the video slot. Shot 7 is the last polite layer failing.",
        grant: "You have the breath. Six seconds of neon she won't redo.",
        story:
          "Motion is the upgrade. Shot 7 is sheer mesh failing — covered climax path, not a nude dump.",
        drop: "78% never see her move on camera.",
        media: "grant:nyx_rev_6.mp4",
        type: "video",
        pos: "center",
        price: P[6],
      },
      {
        id: "nyx_rev_7",
        step: 7,
        title: "Silk",
        tease:
          "Last polite layer — sheer black mesh slip, lace already gone. Still covered cyber editorial. Shot 8 densifies the chrome fail.",
        grant: "The polite layer is failing for you.",
        story:
          "Sheer mesh is the confession. Shot 8 is denser — still vault-safe covered. Shot 9 is the close she priced as climax.",
        drop: "84% never see the slip fail.",
        media: "grant:nyx_rev_7.jpg",
        type: "photo",
        pos: "center",
        price: P[7],
      },
      {
        id: "nyx_rev_8",
        step: 8,
        title: "Chrome Fail",
        tease:
          "Covered editorial densest frame before climax — mesh failing, LED tattoos and anklet stay. Not a nude promise. Shot 9 is the vault close.",
        grant: "Chrome failing for you. Still her rules.",
        story:
          "This is the save-frame before climax. Shot 9 is the last frontal she cleared — covered cyber charge, eyes owning the lens.",
        drop: "89% never get this denser fail.",
        media: "grant:nyx_rev_8.jpg",
        type: "photo",
        pos: "center 40%",
        price: P[8],
      },
      {
        id: "nyx_rev_9",
        step: 9,
        title: "Climax — Vault Close",
        tease:
          "Last frontal. Maximum cyber charge she cleared for the vault — covered editorial, eyes owning the lens. She doesn't reshoot a climax.",
        grant: "Vault close. You finished her frontal set. Covered. Exact.",
        story:
          "You didn't buy a nude dump. You finished a chrome-mesh night she designed so the last frame still feels like ownership.",
        drop: "93% who start never see the vault close.",
        media: "grant:nyx_rev_9.jpg",
        type: "photo",
        pos: "center bottom",
        price: P[9],
        climax: true,
      },
    ],
  },
  {
    id: "lad_nyx_curve",
    slug: "nyx-the-curve",
    title: "The Curve",
    theme: "worship",
    tagline: "She turns when you've earned the chrome back — covered cyber worship.",
    description:
      "Ass worship, shot by shot, neon spill. Over the shoulder, mesh on her spine, then the close-ups collectors replay. Covered editorial — LED hip ink peeks; no nude climax promise.",
    cover: "/media/nyx-00-the-curve-cover.jpg",
    sort: 5,
    collectors: 0,
    climax: 0,
    discount: 0.32,
    shots: [
      {
        id: "nyx_crv_1",
        step: 1,
        title: "Over the Shoulder",
        tease:
          "Back to camera, look over the left shoulder, chrome mesh on. Cheapest way she lets you admit the hunger. Shot 2 is mesh on her spine.",
        grant: "You have the turn. She knows what you came for.",
        story: "The face was a courtesy. The rest is the curve. Shot 2 is the drape.",
        drop: "",
        media: "grant:nyx_crv_1.jpg",
        type: "photo",
        pos: "center 20%",
        price: P[1],
      },
      {
        id: "nyx_crv_2",
        step: 2,
        title: "The Drape",
        tease:
          "Chrome mesh pooled at the small of her back. LED hip tattoo peeks. Shot 3 is the line down.",
        grant: "You have the drape. Patience is being rewarded.",
        story: "The drape is her enjoying the wait. Shot 3 is hips. Stay on the line.",
        drop: "38% admit the hunger, then flinch.",
        media: "grant:nyx_crv_2.jpg",
        type: "photo",
        pos: "center",
        price: P[2],
      },
      {
        id: "nyx_crv_3",
        step: 3,
        title: "The Line",
        tease:
          "From the small of her back down — robe failing on purpose, still covered. Shot 4 she holds.",
        grant: "You have the line. Don't waste it.",
        story: "Hips. The study starts here. Shot 4 she holds longer.",
        drop: "51% never stay on the line long enough.",
        media: "grant:nyx_crv_3.jpg",
        type: "photo",
        pos: "center 30%",
        price: P[3],
      },
      {
        id: "nyx_crv_4",
        step: 4,
        title: "Held",
        tease:
          "Same turn, held longer — hyper-sexual curve, covered cyber. Shot 5 is violet rim light.",
        grant: "She's holding still for you.",
        story: "A held pose is the upgrade. Shot 5 is rim light — the study frame.",
        drop: "61% never get a pose held for them.",
        media: "grant:nyx_crv_4.jpg",
        type: "photo",
        pos: "center 60%",
        price: P[4],
      },
      {
        id: "nyx_crv_5",
        step: 5,
        title: "Violet Light",
        tease:
          "Cool violet rim on the curve. Study frame. Shot 6 is cropped. Honest. Covered.",
        grant: "You have the study frame. Worship starts here.",
        story: "The study is still polite. Shot 6 is cropped. No face required.",
        drop: "70% never get the study.",
        media: "grant:nyx_crv_5.jpg",
        type: "photo",
        pos: "center 70%",
        price: P[5],
      },
      {
        id: "nyx_crv_6",
        step: 6,
        title: "Closer",
        tease:
          "Cropped hips. No face. Honest curve study — covered editorial. Shot 7 is side-lying neon spill.",
        grant: "You have the close study. She isn't performing now.",
        story: "No face means she's done performing. Shot 7 is the curve without the pose.",
        drop: "78% never see her without the performance.",
        media: "grant:nyx_crv_6.jpg",
        type: "photo",
        pos: "center 55%",
        price: P[6],
      },
      {
        id: "nyx_crv_7",
        step: 7,
        title: "On Silk",
        tease:
          "Side-lying, unposed, private neon spill — covered cyber. Shot 8 is the save-frame curve.",
        grant: "You have the unposed curve.",
        story: "Private not postcard. Shot 8 she knows is the save-frame.",
        drop: "84% never get the unposed night.",
        media: "grant:nyx_crv_7.jpg",
        type: "photo",
        pos: "center",
        price: P[7],
      },
      {
        id: "nyx_crv_8",
        step: 8,
        title: "Offered",
        tease:
          "Full curve — she knows this is the save-frame. Still covered editorial. Shot 9 is the worship close.",
        grant: "You have the save-frame.",
        story: "Shot 9 is the last close of the curve she cleared for the vault.",
        drop: "89% never get the offered curve.",
        media: "grant:nyx_crv_8.jpg",
        type: "photo",
        pos: "center 40%",
        price: P[8],
      },
      {
        id: "nyx_crv_9",
        step: 9,
        title: "Climax — Full Worship",
        tease:
          "Last close of the curve — densest covered cyber worship she cleared. No nude promise. She doesn't reshoot worship.",
        grant: "Full worship. You finished at her back. Covered. Exact.",
        story:
          "You finished a ritual she designed so the curve would feel like a throne — chrome and neon, not a nude dump.",
        drop: "93% never see the worship close.",
        media: "grant:nyx_crv_9.jpg",
        type: "photo",
        pos: "center bottom",
        price: P[9],
        climax: true,
      },
    ],
  },
  {
    id: "lad_nyx_pedestal",
    slug: "nyx-the-pedestal",
    title: "The Pedestal",
    theme: "feet",
    tagline: "Chrome stilettos. Silver anklet. She looks down only when you pay.",
    description:
      "Feet / anklet focus. Black chrome stilettos, silver chain anklet, bare soles — nine beats. Pedestal stays vault-honest; late frames are covered editorial studies, not a nude ladder.",
    cover: "/media/nyx-00-the-pedestal-cover.jpg",
    sort: 6,
    collectors: 0,
    climax: 0,
    discount: 0.32,
    shots: [
      {
        id: "nyx_ped_1",
        step: 1,
        title: "Heels",
        tease:
          "Black chrome stilettos, crossed ankles, silver anklet on the standing foot. She has not looked down. Shot 2 she recrosses.",
        grant: "You have the heels. She knows you're looking down.",
        story: "Heels are the costume. Shot 2 is the recross — her noticing you.",
        drop: "",
        media: "grant:nyx_ped_1.jpg",
        type: "photo",
        pos: "center 80%",
        price: P[1],
      },
      {
        id: "nyx_ped_2",
        step: 2,
        title: "The Cross",
        tease:
          "Same legs, recrossed ankles. A woman who recrosses for you is deciding how far the inspection goes. Shot 3 is one foot toward the lens.",
        grant: "You have the recross.",
        story: "The recross is her noticing you. Shot 3 is the extend.",
        drop: "38% look, then pretend they were here for the face.",
        media: "grant:nyx_ped_2.jpg",
        type: "photo",
        pos: "center 85%",
        price: P[2],
      },
      {
        id: "nyx_ped_3",
        step: 3,
        title: "Extended",
        tease:
          "One foot toward the lens, arch, heel still on, anklet. Shot 4 is jewelry close.",
        grant: "You have the extend. You passed the test.",
        story: "The extend is the interview. Shot 4 is silver on the ankle.",
        drop: "51% fail the extend.",
        media: "grant:nyx_ped_3.jpg",
        type: "photo",
        pos: "center 60%",
        price: P[3],
      },
      {
        id: "nyx_ped_4",
        step: 4,
        title: "Anklet",
        tease:
          "Jewelry close — silver chain, heel still a costume. Shoes come off next.",
        grant: "The anklet is yours. Shoes come off next.",
        story: "Jewelry is a private-set signal. Shot 5 is shoes off.",
        drop: "61% never see the anklet this close.",
        media: "grant:nyx_ped_4.jpg",
        type: "photo",
        pos: "center 80%",
        price: P[4],
      },
      {
        id: "nyx_ped_5",
        step: 5,
        title: "Bare",
        tease:
          "Shoes off beside her. Bare sole in frame, anklet stays. Shot 6 she holds the foot still.",
        grant: "Shoes off. The heels were a costume.",
        story: "Bare is the admission. Shot 6 she holds still for you.",
        drop: "70% never get shoes off.",
        media: "grant:nyx_ped_5.jpg",
        type: "photo",
        pos: "center 40%",
        price: P[5],
      },
      {
        id: "nyx_ped_6",
        step: 6,
        title: "Held Still",
        tease:
          "One foot held, no fidget, offered. Shot 7 is soles — the shot this set exists for.",
        grant: "She's holding still. Don't blink.",
        story: "Held still is her side of the ritual. Shot 7 is soles.",
        drop: "78% never get a foot held still for them.",
        media: "grant:nyx_ped_6.jpg",
        type: "photo",
        pos: "bottom",
        price: P[6],
      },
      {
        id: "nyx_ped_7",
        step: 7,
        title: "Soles",
        tease:
          "Both soles — soft, unhurried, covered editorial study. Shot 8 is the close inspection.",
        grant: "You have her soles.",
        story: "Soles are the confession. Shot 8 is the study. Shot 9 is arch + anklet held.",
        drop: "84% never get soles.",
        media: "grant:nyx_ped_7.jpg",
        type: "photo",
        pos: "center",
        price: P[7],
      },
      {
        id: "nyx_ped_8",
        step: 8,
        title: "Study",
        tease:
          "Extreme close of one sole. Private inspection. Shot 9 is the full pedestal close.",
        grant: "You have the study. She let you look this long.",
        story: "This is her letting you look. Shot 9 she doesn't reshoot.",
        drop: "89% never get the inspection.",
        media: "grant:nyx_ped_8.jpg",
        type: "photo",
        pos: "center 20%",
        price: P[8],
      },
      {
        id: "nyx_ped_9",
        step: 9,
        title: "Climax — Full Pedestal",
        tease:
          "Arch + sole + silver anklet, held. Last inspection. She doesn't redo this because you got cheap on the floor.",
        grant: "Full pedestal. You finished at her feet.",
        story:
          "You finished a ritual she designed so the floor would feel like a throne — chrome heels to bare sole, anklet on.",
        drop: "93% who start never see the last inspection.",
        media: "grant:nyx_ped_9.jpg",
        type: "photo",
        pos: "center bottom",
        price: P[9],
        climax: true,
      },
    ],
  },
];
