/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiThemeRouteImport } from './routes/api.theme'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as CheckoutInvoiceIdRouteImport } from './routes/checkout.$invoiceId'
import { Route as GiftCodeRouteImport } from './routes/gift.$code'
import { Route as LaddersSlugRouteImport } from './routes/ladders.$slug'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaShotIdRouteImport } from './routes/api/media.$shotId'
import { Route as ApiPaymentsIpnRouteImport } from './routes/api/payments.ipn'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'
import { Route as LegalModelsSlugRouteImport } from './routes/legal.models.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemeRoute = ApiThemeRouteImport.update({
  id: '/api/theme',
  path: '/api/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutInvoiceIdRoute = CheckoutInvoiceIdRouteImport.update({
  id: '/checkout/$invoiceId',
  path: '/checkout/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeRoute = GiftCodeRouteImport.update({
  id: '/gift/$code',
  path: '/gift/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LaddersSlugRoute = LaddersSlugRouteImport.update({
  id: '/ladders/$slug',
  path: '/ladders/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaShotIdRoute = ApiMediaShotIdRouteImport.update({
  id: '/api/media/$shotId',
  path: '/api/media/$shotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIpnRoute = ApiPaymentsIpnRouteImport.update({
  id: '/api/payments/ipn',
  path: '/api/payments/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)
const LegalModelsSlugRoute = LegalModelsSlugRouteImport.update({
  id: '/legal/models/$slug',
  path: '/legal/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/checkout/$invoiceId': typeof CheckoutInvoiceIdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/ladders/$slug': typeof LaddersSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/legal/': typeof LegalIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$shotId': typeof ApiMediaShotIdRoute
  '/api/payments/ipn': typeof ApiPaymentsIpnRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/legal/models/$slug': typeof LegalModelsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/checkout/$invoiceId': typeof CheckoutInvoiceIdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/ladders/$slug': typeof LaddersSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/legal': typeof LegalIndexRoute
  '/models': typeof ModelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$shotId': typeof ApiMediaShotIdRoute
  '/api/payments/ipn': typeof ApiPaymentsIpnRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/legal/models/$slug': typeof LegalModelsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/checkout/$invoiceId': typeof CheckoutInvoiceIdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/ladders/$slug': typeof LaddersSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/legal/': typeof LegalIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$shotId': typeof ApiMediaShotIdRoute
  '/api/payments/ipn': typeof ApiPaymentsIpnRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/legal/models/$slug': typeof LegalModelsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connectors'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vault'
    | '/api/mcp'
    | '/api/theme'
    | '/api/v1'
    | '/checkout/$invoiceId'
    | '/gift/$code'
    | '/ladders/$slug'
    | '/legal/$slug'
    | '/models/$slug'
    | '/legal/'
    | '/models/'
    | '/api/auth/$'
    | '/api/media/$shotId'
    | '/api/payments/ipn'
    | '/api/v1/$'
    | '/legal/models/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connectors'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vault'
    | '/api/mcp'
    | '/api/theme'
    | '/api/v1'
    | '/checkout/$invoiceId'
    | '/gift/$code'
    | '/ladders/$slug'
    | '/legal/$slug'
    | '/models/$slug'
    | '/legal'
    | '/models'
    | '/api/auth/$'
    | '/api/media/$shotId'
    | '/api/payments/ipn'
    | '/api/v1/$'
    | '/legal/models/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connectors'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vault'
    | '/api/mcp'
    | '/api/theme'
    | '/api/v1'
    | '/checkout/$invoiceId'
    | '/gift/$code'
    | '/ladders/$slug'
    | '/legal/$slug'
    | '/models/$slug'
    | '/legal/'
    | '/models/'
    | '/api/auth/$'
    | '/api/media/$shotId'
    | '/api/payments/ipn'
    | '/api/v1/$'
    | '/legal/models/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnectorsRoute: typeof ConnectorsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaultRoute: typeof VaultRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiThemeRoute: typeof ApiThemeRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  CheckoutInvoiceIdRoute: typeof CheckoutInvoiceIdRoute
  GiftCodeRoute: typeof GiftCodeRoute
  LaddersSlugRoute: typeof LaddersSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaShotIdRoute: typeof ApiMediaShotIdRoute
  ApiPaymentsIpnRoute: typeof ApiPaymentsIpnRoute
  LegalModelsSlugRoute: typeof LegalModelsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theme': {
      id: '/api/theme'
      path: '/api/theme'
      fullPath: '/api/theme'
      preLoaderRoute: typeof ApiThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$invoiceId': {
      id: '/checkout/$invoiceId'
      path: '/checkout/$invoiceId'
      fullPath: '/checkout/$invoiceId'
      preLoaderRoute: typeof CheckoutInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$code': {
      id: '/gift/$code'
      path: '/gift/$code'
      fullPath: '/gift/$code'
      preLoaderRoute: typeof GiftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladders/$slug': {
      id: '/ladders/$slug'
      path: '/ladders/$slug'
      fullPath: '/ladders/$slug'
      preLoaderRoute: typeof LaddersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$shotId': {
      id: '/api/media/$shotId'
      path: '/api/media/$shotId'
      fullPath: '/api/media/$shotId'
      preLoaderRoute: typeof ApiMediaShotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/ipn': {
      id: '/api/payments/ipn'
      path: '/api/payments/ipn'
      fullPath: '/api/payments/ipn'
      preLoaderRoute: typeof ApiPaymentsIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/legal/models/$slug': {
      id: '/legal/models/$slug'
      path: '/legal/models/$slug'
      fullPath: '/legal/models/$slug'
      preLoaderRoute: typeof LegalModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnectorsRoute: ConnectorsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaultRoute: VaultRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiThemeRoute: ApiThemeRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  CheckoutInvoiceIdRoute: CheckoutInvoiceIdRoute,
  GiftCodeRoute: GiftCodeRoute,
  LaddersSlugRoute: LaddersSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  LegalIndexRoute: LegalIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaShotIdRoute: ApiMediaShotIdRoute,
  ApiPaymentsIpnRoute: ApiPaymentsIpnRoute,
  LegalModelsSlugRoute: LegalModelsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
